version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blog
    restart: unless-stopped

  blog:
    image: ${DOCKER_USERNAME}/blog:${IMAGE_TAG:-latest}
    expose:
      - "5000"
    volumes:
      - blog_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  blog_data:
    name: blog_data