version: '3.8'

services:
  blog:
    image: ${DOCKER_USERNAME}/blog:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    volumes:
      - blog_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  blog_data:
    name: blog_data